DROP TABLE IF EXISTS giay_phep CASCADE;
DROP TABLE IF EXISTS tai_lieu CASCADE;
DROP TABLE IF EXISTS ho_so_tai_lieu CASCADE;
DROP TABLE IF EXISTS ho_so CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS loai_tai_lieu CASCADE;
DROP TABLE IF EXISTS doanh_nghiep CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
